#!/bin/bash

debug=true

dbg()
{
	    $debug && echo $@ 
#	    $debug && echo $* 
}

# dbg "yoni is here"

for (( i=0,part_start=0 ; i<4 ; i+=1 )) ; do
	if [ $i -lt 3 ]; then
		dbg "less equal 3"
	else
		dbg "never"
	fi
done
																							
