#!/bin/bash

size=${1:-10}
echo Reading ${size} MB
./yonilog rd${size}MB

/home/fig/tools/lmdd-i686 of=internal ipat=1 if=/dev/raw/raw1 bs=1m count=${size}
#/home/fig/tools/lmdd-i686 of=internal ipat=1 if=/dev/sda bs=1m count=${size}
