#!/bin/bash
size=${1:-10}
echo Writing ${size} MB
./yonilog ${size}MB

/home/fig/tools/lmdd-i686 if=internal opat=1 of=/dev/raw/raw1 bs=1m count=${size}
#/home/fig/tools/lmdd-i686 if=internal opat=1 of=/dev/sda bs=1m count=${size}

